### ISSUE TITLE
Curiosidades sobre DOALL

### ISSUE THREAD

**Issue by rockersuke** [Utodev/PCDAAD#3]
Pequeñas diferencias de comportamiento de DOALL en PCDAAD 1.2 (Mislata, el último que me pasate, vamos) respecto de los intérpretes originales:

DAAD clásico no permite anidar DOALLs e interrumpirá inmediatamente el juego con un Runtime error 4 tal y como avisa el manual.
PCDAAD sí que lo permite, lo cual puede considerarse incorrecto o interesante según se mire. En manos cuidadosas permitiría hacer cosas que el original no podría. Ahora bien:
Consideremos 2 DOALL anidados, llamémosles PADRE e HIJO:
Si HIJO está en el mismo proceso que PADRE al interrumpirse HIJO (o bien simplemente completarse por primera vez) se interrumpirá también PADRE tanto si le tocaba como si no.
Ésto no sucederá, sin embargo, si HIJO está en un proceso distinto de PADRE, es decir, dentro del DOALL PADRE se llama a otro proceso y el DOALL HIJO está dentro de éste. En ese caso PADRE e HIJO completarían sus respectivas iteraciones anidadas como cabría esperar.
Pero...
Ahora ya independientemente de que haya anidaciones o no.
DOALL en PCDAAD funciona parentemente bien para ejecutar acciones COGER y DEJAR normalitas, como en las plantillas base, pero si el autor pretende crear una propia puede pasar algo raro.
Pongamos que ponemos un verbo XYZZY en el vocabulario y en PRO 5 hacemos que XYZZY invoque un sencillo DOALL que emita un mensaje por cada objeto presente (HERE), tal que así:

XYZZY   _       DOALL HERE
                MESSAGE "Objeto HERE: _"
                
Si hay objetos presentes en la localidad no se percibirá ninguna anomalía, pero si no los hubiera el DOALL se ejecutará con el último objeto sobre el que se haya realizado alguna acción, aunque sea un simple EX, o, en su defecto, con el primer objeto de la lista de objetos en lugar de salir con un "No puedes hacer eso" que es lo que haría el original.

En el fichero de ejemplo enlazado hay varios objetos en la localidad al sur de la de inicio. XYZZY realizará un DOALL HERE en PRO 5 y llamará a PRO 8 donde intentará un DOALL CARRIED.
Se pueden hacer pruebas comentando y/o descomentando la llamada a PRO 8, haciendo XYZZYs en la localidad donde están los objetos o en las que no, llevando o no llevando cosas, y comparar con cualquiera de los intérpretes clásicos:

https://drive.google.com/file/d/1eF5feignqlGEPK_HgXp4bU6fE_1FfVdd/view?usp=sharing

Prueba a compilar y ejecutar con DAAD Ready para MSDOS (usando PCDAAD 1.2) y nada más empezar teclea algo como EX GAFAS (las gafas no están ahí y te dirá que no, hasta ahí normal) e inmediatamente después un XYZZY. Luego ve al sur, donde están todos los objetos y prueba XYZZY otra vez. Muy curioso todo :-)

**Comment by Utodev** [comment]
Now PCDAAD properly fails when DOALL is executed while in DOALL already. Also, if no objects match the DOALL, it will properly fail also with SYSMESS 9 (You can't do that).

Despite of that, if PCDAAD is called with the -ndoall parameter (nested doalls), then nested DOALLs will be allowed as long as they are not nested in the same process (nested DOALL must be in a different process, called by the first DOALL).
