### ISSUE TITLE
DOALL no se salta la acción cuando NOUN y NOUN2 coinciden.

### ISSUE THREAD

**Issue by rockersuke** [Utodev/PCDAAD#4]
Probando con el PCDAAD y el JDAAD incluidos en el último DAAD-Ready 8 me encontré una cosa curiosa. Llevaba un objeto contenedor, una caja, y otro par de objetos normales, un libro y una pistola. Tenía programada una acción METER TODO en CAJA en la cual, efectivamente, metía el libro y la pistola en la caja y... después metía la caja en la caja, con lo que ésta desaparecía del juego a efectos prácticos (se la llevaba a su localidad asignada) 0_0!!
Lo más fino que he tenido tiempo de atinar es que parece ser que el DOALL de PCDAAD y JDAAD no ejecuta la parte del paso 2 de la descripción de DOALL del manual que dice lo de: "If Noun(Adjective)1 matches Noun(Adjective)2 then a return is made to step 1. This  implements the "Verb ALL EXCEPT object" facility of the parser."

**Comment by Utodev** [comment]
Cierto. Parece que la execepción que hace que funcione el EXCEPT no está implementada, lo cual hace que se produzca ese mismo efecto en el que un contenedor se mete dentro de si mismo. 

Ha quedado solucionado en el repositorio, por si fuera necesario recompilar. En breve habrá un DAAD Ready 0.8.1, de todos modos, por lo que pronto habrá un binario nuevo.

**Comment by Utodev** [comment]
Fixed!
